"""Parse plaintiffs and defendants from xml legal complaint generated by FineReader"""
__author__      = "Walker Herring"

import xml.etree.ElementTree as ET

ABBYY_NS = '{http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml}'

def get_defendants_from_xml(xml_text):
    root = ET.fromstring(xml_text)

    defendants_found = False
    defendants_str = ''
    for line in root.iter(ABBYY_NS + 'line'):

        text = line.find(ABBYY_NS + 'formatting').text

        if text is not None:

            if defendants_found:
                if 'Defendants.' in text:
                    return str_cleanup(defendants_str)
                else:
                    defendants_str += ' ' + text

            elif 'vs.' in text or 'v.' in text:
                defendants_found = True

def str_cleanup(string):
    return string.strip()

def get_plaintiffs_from_xml(xml_text):
    root = ET.fromstring(xml_text)

    return 'NOT IMPLEMENTED'